// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 03 Jun 2015 13:59:28 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.4.18503.0")]
[assembly: AssemblyFileVersion("1.4.18503.1359")]
