// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 03 Jun 2015 13:47:44 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.3.18503.0")]
[assembly: AssemblyFileVersion("1.3.18503.1347")]
